version: 2
updates:
  - package-ecosystem: maven
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '23:00'
      timezone: 'Europe/Amsterdam'
    labels:
      - "build infrastructure"
      - "dependencies"

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '23:00'
      timezone: 'Europe/Amsterdam'
    labels:
      - "build infrastructure"
