tag-template: "kadaster-gds2-$NEXT_MINOR_VERSION"
name-template: v$NEXT_MINOR_VERSION 🎁

version-template: "$MAJOR.$MINOR"

template: |
  ## Aanpassingen

  $CHANGES
  
categories:
  - title: 🚨 Verwijderd
    when:
      label: removed
  - title: ⚠️ Deprecated
    when:
      label: deprecated
  - title: 🚀 Nieuw en Verbeterd
    when:
      labels:
        - enhancement
        - feature
  - title: 🐛 Bug Fixes
    when:
      labels:
        - bug
        - fix
        - bugfix
        - regression
  - title: 📖 Documentatie
    when:
      label: documentation
  - title: 🔨 Dependency updates
    when:
      label: dependencies
  - title: 🚦 Tests
    when:
      labels:
        - tests
  - title: 🔨 Infra
    when:
      labels:
        - build infrastructure

replacers:
  - search: '/CVE-(\d{4})-(\d+)/g'
    replace: 'https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-$1-$2'
