name: Maven build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  check_keystore:
    name: 'Check keystore'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: 'Check keystore'
        run: |    
         ./jks-certificate-expiry-checker.sh --keystore ./src/main/resources/pkioverheid.jks --password changeit -t90 

  build:
    name: Java ${{ matrix.java }} build
    runs-on: ubuntu-latest
    needs: check_keystore
    strategy:
      matrix:
        java: [ 11 ]
        java-dist: [ 'temurin' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Set up JDK for build
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: ${{ matrix.java-dist }}

      - name: Inspect environment
        run: |
          set | grep JAVA

      - name: Install
        run: mvn -V -B -e install

      - name: Javadoc
        run: |
          mvn javadoc:javadoc
          mvn javadoc:test-javadoc

      - name: Site
        run: mvn -B -e site site:stage


  deploy:
    name: Deploy artifacts
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
    if: ${{ github.ref == 'refs/heads/master' && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Build and Push
        # no need to run any QC or tests
        env:
          REPO_B3P_ACTOR: ${{ secrets.REPO_B3P_ACTOR }}
          REPO_B3P_TOKEN: ${{ secrets.REPO_B3P_TOKEN }}
        run: |
          mvn -B -V -fae -Dmaven.test.skip=true clean deploy --settings .github/maven-settings.xml


  cleanup:
    name: Maven cache cleanup
    if: ${{ always() }}
    needs: [ build, deploy ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Cleanup snapshot cache
        run: |
          find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
