name: Maven build

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: Java ${{ matrix.java }} build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Set up JDK for build
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'

      - name: Inspect environment
        run: |
          set | grep JAVA

      - name: Install
        run: mvn -V -B -e install --global-toolchains .github/ubuntu-toolchains.xml

      - name: Javadoc
        run: |
          mvn javadoc:javadoc --global-toolchains .github/ubuntu-toolchains.xml
          mvn javadoc:test-javadoc --global-toolchains .github/ubuntu-toolchains.xml

      - name: Site
        run: mvn -B -e site site:stage --global-toolchains .github/ubuntu-toolchains.xml


  deploy:
    name: Deploy artifacts
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
      contents: read
    if: ${{ github.ref == 'refs/heads/master' && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' ) }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Build and Push
        # no need to run any QC or tests
        env:
          REPO_B3P_ACTOR: ${{ secrets.REPO_B3P_ACTOR }}
          REPO_B3P_TOKEN: ${{ secrets.REPO_B3P_TOKEN }}
        run: |
          mvn -B -V -fae -Dmaven.test.skip=true clean deploy --settings .github/maven-settings.xml --global-toolchains .github/ubuntu-toolchains.xml


  cleanup:
    name: Maven cache cleanup
    if: ${{ always() }}
    needs: [ build, deploy ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-

      - name: Cleanup snapshot cache
        run: |
          find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
