name: GH OWASP dependency check

on: [push]

jobs:
  build:
    name: OWASP dependency check
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2.1.3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 11
    - name: OWASP Dependency Check
      run: mvn org.owasp:dependency-check-maven:check -fae -B -Dorg.slf4j.simpleLogger.defaultLogLevel=WARN -DfailBuildOnCVSS=7 
    - name: Remove any SNAPSHOT jars from repository
      run: |
        find ~/.m2/repository -name "*SNAPSHOT*" -type d | xargs rm -rf {}
